responses:
  privateGroup:
    description: Private group
    content:
      application/json:
        schema:
          $ref: "#/responses/schemas/privateGroup"
  schemas:
    privateGroup:
      type: object
      properties:
        name: 
          type: string
          example: transerve
        description:
          type: string
          example: this group for transerve team
        createdBy:
          type: string
          example: 9uiewjf9023jfo39ur39
        members:
          type: array
          items:
            type: string
        is_active:
          type: boolean
          