responses:
  schemas:
    Trackable:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
          example: "2019-08-28T12:38:39.258+00:00"
        modifiedAt:
          type: string
          format: date-time
          example: "2019-08-28T12:40:27.316+00:00"
    DocumentContent:
      allOf:
        - $ref: '#/responses/schemas/Trackable'
        - type: object
        - properties:
            id:
              type: string
              format: uniqueid
              example: 54313797101372181
            name: 
              type: string
              example: Proposal Document
            description:
              type: string
              example: This is a proposal document that covers the plan to execute and the cost and time estimates
            fileName:
              type: string
              example: proposal.pdf
            tags:
              type: array
              items: 
                type: string
              example: ["finance", "proposal"]
            themes:
              type: array
              items: 
                type: string
              example: ["maturation", "global", "proposal"]
    Document:
      allOf:
        - $ref: '#/responses/schemas/DocumentContent'
        - type: object
        - properties:
            owner:
              type: object
              properties:
                name:
                  type: string
                  example: Amarthya Sen
                id:
                  type: string
                  example: 54213790101372682
            status:
              type: string
              enum: ["unpublished", "published", "deleted", "pending-approval", "rejected"]
              example: published
            versionNumber:
              type: integer
              description: Latest published version number
              example: 1
            versionId:
              type: string
              format: uniqueid
              example: 54313797101372179
    DocumentVersion:
      allOf:
        - $ref: '#/responses/schemas/DocumentContent'
        - type: object
        - properties:
            versionNumber:
              type: number
              example: 1
            documentId:
              type: string
              format: uniqueid
              example: 54213790101372681
            status:
              type: string
              enum: ["draft", "submitted", "rejected"]
    DocPermissions:
        allOf:
          - $ref: "#/responses/schemas/UserSuggestion"
          - type: object
            required: 
              - permission
            properties:
              permission:
                type: string
                enum: ["owner", "collaborator", "viewer"]
            
      UserSuggestion:
        type: object
        required: 
          - id
        properties:
          id:
            type: string
            example: 12345432112424
            description: groupId or userId
          name:
            type: string
            example: hello
            description: group name or user name
          email:
            type: string
            example: jeevan+23@transerve.com
            description: user or group email
          type: 
            type: string
            example: user
            enum: ["group", "user"]