responses:
  project:
    description: project
    content:
      application/json:
        schema:
          $ref: "#/schemas/projectSchema"
  schemas:
    projectSchema:
      type: object
      properties:
        name: 
          type: string
          example: vizag schools develop
        city:
          type: string
          example: vizag
        summary:
          type: string
          example: this project for de develop schools
        reference: 
          type: string
          example: VIZAG-CODE
        bannerImage:
          type: string
          example: https://amazonS3.com/project/banner
        maturationStartDate:
          type: array
          items:
            type: object
            properties:
              date: 
                type: string
                example: 22-1-2019
              created_at: 
                type: string
                example: 10-1-2019
              modified_at: 
                type: string
                example: 15-1-2019
              modified_by:
                type: string
                example: 12343567890
                description: user id
        thirdParyAggrementDate:
          type: array
          items:
            type: object
            properties:
              date: 
                type: string
                example: 22-1-2019
              created_at: 
                type: string
                example: 10-1-2019
              modified_at: 
                type: string
                example: 15-1-2019
              modified_by:
                type: string
                example: 12343567890
                description: user id
        thirdParyAggrementDocument:
          type: array
          items:
            type: object
            properties:
              date: 
                type: string
                example: https://Amazons3.com/thirdPary/Aggrement/Document
              created_at: 
                type: string
                example: 10-1-2019
              modified_at: 
                type: string
                example: 15-1-2019
              modified_by:
                type: string
                example: 12343567890
                description: user id
        maturationEndDate:
          type: array
          items:
            type: object
            properties:
              date: 
                type: string
                example: 22-1-2019
              created_at: 
                type: string
                example: 10-1-2019
              modified_at: 
                type: string
                example: 15-1-2019
              modified_by:
                type: string
                example: 12343567890
                description: user id
        projectCost:
          type: number
          example: 12343
        citiisGrants:
          type: number
          example: 12343
        fundsReleased:
            type: array
            items:
              type: object
              properties:
                date: 
                  type: number
                  example: 1000
                created_at: 
                  type: string
                  example: 10-1-2019
                modified_at: 
                  type: string
                  example: 15-1-2019 
                modified_by:
                  type: string
                  example: 12343567890
                  description: user id
        fundsUtilised:
            type: array
            items:
              type: object
              properties:
                date: 
                  type: number
                  example: 1000
                created_at: 
                  type: string
                  example: 10-1-2019
                modified_at: 
                  type: string
                  example: 15-1-2019 
                modified_by:
                  type: string
                  example: 12343567890
                  description: user id
        fundsUtilisedDocuments:
            type: array
            items:
              type: object
              properties:
                date: 
                  type: string
                  example: https://Amazons3.com/fundsUtilised/Documents
                created_at: 
                  type: string
                  example: 10-1-2019
                modified_at: 
                  type: string
                  example: 15-1-2019 
                modified_by:
                  type: string
                  example: 12343567890
                  description: user id
        themes: 
          type: string
          example: 12343567890
          description: theme id
        is_active: 
          type: boolean
          example: true
        phase:
          type: string
          example: phase id

    city_names:
      type: object
      properties:
        state: 
          type: string
          example: Andhra Pradesh
        cities:
          type: array
          items:
            type: string
          example:
            - Vizag
            - Vizianagaram