schemas:
  riskSchema:
    type: object
    properties:
      riskFamily:
        type: string 
      description: 
        type: string         
      phase:
        type: string 
      impact:
        type: number
      probability:
        type: number
      actions: 
        type: string 
      comments: 
        type: string
      riskProvision:
        type: number
      riskOwner: 
        type: string 
      status: 
        type: string
      previousTrend: